version: "3"

services: 
  php:
    build: .
    container_name: app
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./app:/var/www/html
      - ./sites-enabled:/etc/apache2/sites-enabled
    networks:
      - rede
  database:
      image: mysql:8.0.30-debian
      restart: always
      ports:
        - 13306:3306
      environment:
        MYSQL_ROOT_PASSWORD: P@55w0rd
        MYSQL_DATABASE: app
        MYSQL_USER: dbadmin
        MYSQL_PASSWORD: P@55w0rd
      volumes:
        - "./db:/var/lib/mysql"
      networks:
        - rede
volumes:
    data:
networks:
  rede:
    driver: bridge
