version: "3"

services: 
  php:
    build: .
    container_name: api-appAj
    ports:
      - 81:80
    volumes: 
      - ./api:/var/www/html
    networks:
      - rede
  database:
      image: mysql:5.7.20
      restart: always
      ports:
        - 33306:3306
      environment:
        MYSQL_ROOT_PASSWORD: 1qazxsw2
        MYSQL_DATABASE: ajdb
        MYSQL_USER: dbadmin
        MYSQL_PASSWORD: 1qazxsw2
      volumes:
        - "./db:/var/lib/mysql"
      networks:
        - rede
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /spec/swagger.json
    volumes:
        - ./doc:/spec
volumes:
    data:
networks:
  rede:
    driver: bridge
