version: "3"

services: 
  php:
    build: .
    container_name: app
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./app:/var/www/html
    networks:
      - rede
  database:
      image: mysql:5.7.20
      restart: always
      ports:
        - 13306:3306
      environment:
        MYSQL_ROOT_PASSWORD: mudarSenha
        MYSQL_DATABASE: app
        MYSQL_USER: dbadmin
        MYSQL_PASSWORD: mudarSenha
      volumes:
        - "./db:/var/lib/mysql"
      networks:
        - rede
volumes:
    data:
networks:
  rede:
    driver: bridge
